from tkinter import *
hamdy=Tk()
hamdy.geometry('500x500')

botton1=Button(hamdy,text='circle', cursor='circle')  
botton1.pack()
botton2=Button(hamdy,text='plus', cursor='plus')  
botton2.pack()
botton3=Button(hamdy,text='mouse', cursor='mouse')  
botton3.pack()
botton4=Button(hamdy,text='target', cursor='target')  
botton4.pack()
botton5=Button(hamdy,text='cross', cursor='cross')  
botton5.pack()
botton6=Button(hamdy,text='clock', cursor='clock')  
botton6.pack()
botton7=Button(hamdy,text='heart', cursor='heart')  
botton7.pack()
botton8=Button(hamdy,text='spider', cursor='spider')  
botton8.pack()
botton9=Button(hamdy,text='sizing', cursor='sizing')  
botton9.pack()
botton9=Button(hamdy,text='trek', cursor='trek')  
botton9.pack()

label1=Label(hamdy,text='omfbilnerbm;erknblernb' , cursor='man')
label1.pack()

hamdy.mainloop()